### ISSUE TITLE
[Feature Request] Bulletproof syntax

### ISSUE THREAD

**Issue by Kristinita** [WebFont/webfont#3]
*(Если не возражаете, по-русски буду писать)*

### 1. Summary

Хотелось бы «Пуленепробиваемый синтаксис» для @font-face. [**По всей видимости**](http://blog.fontspring.com/2011/02/the-new-bulletproof-font-face-syntax/), это лучше в плане кроссбраузерности.

### 2. Expected behavior

Пример, как в моём css выглядят другие шрифты. Конвертирую через [**@font-face generator**](https://everythingfonts.com/font-face).

```css
@font-face
{
    font-family: 'SashaWow';

    src: url('../../fonts/SashaWow/SashaWow.eot');
    src: url('../../fonts/SashaWow/SashaWow.eot?#iefix') format('embedded-opentype'),
    url('../../fonts/SashaWow/SashaWow.woff') format('woff'),
    url('../../fonts/SashaWow/SashaWow.ttf') format('truetype');
}
```

### 3. Actual behavior

Как выглядит css шрифта, который скачал с webfont.ru:

```css
@font-face {
    font-family: 'AleksandraC';
    src: local('AleksandraCRegular'), url('../../fonts/AleksandraC/aleksandracregular.woff2') format('woff2'), url('../../fonts/AleksandraC/aleksandracregular.woff') format('woff'), url('../../fonts/AleksandraC/aleksandracregular.ttf') format('truetype');
    font-weight: 400;
    font-style: bold;
}
```

### 4. Steps to reproduce

Скачал пакет WebFont через Package Contol → загрузил и подключил шрифт AleksandraC → когда открыт css-файл с @font-face, [**csslint выдаёт ошибку**](https://github.com/CSSLint/csslint/wiki/Bulletproof-font-face) в status bar:

> @font-face declaration doesn't follow the fontspring bulletproof syntax. Use the bulletproof @font-face syntax to avoid 404's in old IE (http://www.fontspring.com/blog/the-new-bulletproof-font-face-syntax). (bulletproof-font-face)

### 5. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126
**csslint**
v1.0.4

Спасибо.

**Comment by WebFont** [comment]
Bulletproof синтаксис в данном случае заключается в поддержке IE <= 8. Мы перестали его поддерживать примерно 2,5 года назад. И уже тогда никто не был против. Возвращаться к его поддержке мы не будем точно.

Файл стилей шрифта AleksandraC выглядит иначе, чем в вашем примере
```css
@font-face {
    font-family: 'AleksandraC';
    src: local('AleksandraCRegular'), url('aleksandracregular.woff2') format('woff2'), url('aleksandracregular.woff') format('woff'), url('aleksandracregular.ttf') format('truetype');
    font-weight: 400;
    font-style: normal;
}
```
